baseURL = 'http://quatl.ooo/'
languageCode = 'en-us'
title = 'quatloo'
theme = 'devise'
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true

# Main menu items
[menu]
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "All Posts"
  #   title = "Posts"
  #   url = "/posts/"
  #   weight = -100
  # [[menu.main]]
  #   identifier = "categories"
  #   name = "Categories"
  #   title = "Categories"
  #   url = "/categories/"
  #   weight = -90
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -80
  # [[menu.main]]
  #   identifier = "pdf"
  #   name = "Hire me (pdf)"
  #   title = "CV"
  #   url = "/resume/resume.pdf"
  #   weight = -70

# Configuration Features
[params]
  description = "Project site!"              # Your meta description of the site
  header_title = "graevy"                    # Your header title
  header_subtitle = "Wetware Developer"      # Your header subtitle
  # home_image = "graevy.png"                  # Path to header image starting from the static directory (optional)
  favicon = "/favicon.ico"                   # Path to favicon image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  # copyright = "&copy; Copyright Year, Your Name"
  [params.style]                             # CSS style overrides
    backgroundColor = "#060608"
    homeImageBorderColor = "#95d550"
    fontColor = "#95d550"
    fontFamilyBase = "Liberation Mono"
    codeColor = "#e83e8c"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/graevy"      # Link to associate with icon (http://, https://, mailto:)
  # [[params.social]]
  #   fa_icon = "fab fa-linkedin-in fa-1x"
  #   href = "https://www.linkedin.com/in/avery-mallet-lawrence/"
  # [[params.social]]
  #   fa_icon = "fab fa-twitter fa-1x"
  #   href = ""
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "mailto:avry@pm.me"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
